name: "Tado Assistant (Ingress)"
version: "1.2.0"
slug: tado_assistant
description: "Tado Assistant"

arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386

startup: services
boot: auto

# verhindert docker --init (tini) => s6 bleibt PID1
init: false

# erlaubt Zugriff auf Supervisor/Core API via http://supervisor/... und SUPERVISOR_TOKEN
hassio_api: true

options:
  poll_seconds: 300
  presence_poll_seconds: 60
  ha_presence_entity: "group.family"
  enable_raw_sensors: true
  enable_open_window: true
  open_window_poll_seconds: 120
  zones_refresh_seconds: 21600

  mqtt_enabled: true
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: null
  mqtt_password: null
  mqtt_topic_prefix: "tado_assistant"
  mqtt_discovery_prefix: "homeassistant"

schema:
  poll_seconds: int(5,3600)
  presence_poll_seconds: int(30,86400)
  ha_presence_entity: str?
  enable_raw_sensors: bool
  enable_open_window: bool
  open_window_poll_seconds: int(30,3600)
  zones_refresh_seconds: int(300,86400)
  mqtt_enabled: bool
  mqtt_host: str?
  mqtt_port: int(1,65535)
  mqtt_username: str?
  mqtt_password: password?
  mqtt_topic_prefix: str?
  mqtt_discovery_prefix: str?
