name: "Tado Assistant (Ingress)"
version: "0.3.7"
slug: tado_assistant
description: "Tado Assistant"
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386

startup: services
boot: auto

ingress: true
ingress_port: 8099
ingress_entry: /

webui: "http://[HOST]:[PORT:8099]/"

map:
  - data:rw
